// STATE TRANSITIONS — the fighter under scripted input on a stub model.
import * as THREE from 'three';
import { Fighter, DASH_BURST } from '../src/combat/fighter.js';
import { makeClips } from '../src/art/anim/index.js';
import { CONFIGS } from '../src/roster/configs/all.js';
import { emptyFrame } from '../src/combat/input.js';
import { eq, ok, near } from './assert.mjs';

function stubModel() { return { bones: new Map(), group: new THREE.Group(), palette: { accent: 0xffffff, energy: 0xffffff }, setEnergy() {}, resetSprings() {}, update() {}, setVisible() {}, dispose() {} }; }
export function makeFighter(id = 'yuji', index = 0) { return new Fighter({ config: CONFIGS[id], model: stubModel(), clips: makeClips(id), index }); }
const ctx = (f, opp) => ({ match: null, opponent: opp, effects: { fire() {}, special() { return true; }, blackFlash() {}, assassinate() {} }, domains: { isMyDomain: () => false, castDomain() {}, dismiss() {}, enemyDomainOn: () => false }, camYaw: null });
const frame = (o = {}) => { const f = emptyFrame(); Object.assign(f, o); for (const k in o) if (typeof o[k] === 'boolean' && o[k]) f[k + 'P'] = true; return f; };
const until = (f, opp, state, max = 400) => { for (let i = 0; i < max; i++) { if (f.state === state) return i; f.update(frame(), ctx(f, opp)); f.events.length = 0; } throw new Error('never reached ' + state + ' (in ' + f.state + ')'); };
const run = (f, opp, inp, n) => { for (let i = 0; i < n; i++) { f.update(i === 0 ? inp : frame({ ...inp, punch: false, heavy: false, jump: false }), ctx(f, opp)); f.events.length = 0; } };

export async function suite(t) {
  console.log('fighter');
  t('starts idle, walks, runs, and returns to idle', () => { const f = makeFighter(); const o = makeFighter('megumi', 1); f.setState('idle', {}); run(f, o, frame({ move: { x: 0, z: -0.4 } }), 3); eq(f.state, 'walk'); run(f, o, frame({ move: { x: 0, z: -1 } }), 3); eq(f.state, 'run'); run(f, o, frame(), 3); eq(f.state, 'idle'); });
  t('the punch string chains 1-2-3 and the third launches', () => { const f = makeFighter(); const o = makeFighter('megumi', 1); f.setState('idle', {}); run(f, o, frame({ punch: true }), 1); eq(f.state, 'attack'); eq(f.move.index, 0); const m = f.move; run(f, o, frame({ punch: true }), m.startup + m.active + 3); eq(f.move.index, 1, 'second punch queued'); const m2 = f.move; run(f, o, frame({ punch: true }), m2.startup + m2.active + 3); eq(f.move.index, 2); eq(f.move.type, 'launcher'); });
  t('the heavy costs stamina and refuses without it', () => { const f = makeFighter(); const o = makeFighter('megumi', 1); f.setState('idle', {}); f.res.stamina = 5; run(f, o, frame({ heavy: true }), 1); ok(f.state !== 'attack'); f.res.stamina = 100; run(f, o, frame({ heavy: true }), 1); eq(f.state, 'attack'); eq(f.move.kind, 'heavy'); ok(f.res.stamina < 100 - f.cfg.heavy.staminaCost + 1, 'stamina spent'); });
  t('a technique spends CE, enters ct, and comes back to idle', () => { const f = makeFighter('gojo'); const o = makeFighter('megumi', 1); f.setState('idle', {}); const ce = f.res.curCE; run(f, o, frame({ ct1: true }), 1); eq(f.state, 'ct'); near(f.res.curCE, ce - f.cfg.ct1.cost); const m = f.move; run(f, o, frame(), m.startup + m.active + m.recovery + 1); eq(f.state, 'idle'); });
  t('no CE means no technique', () => { const f = makeFighter('gojo'); const o = makeFighter('megumi', 1); f.setState('idle', {}); f.res.curCE = 0; run(f, o, frame({ ct1: true }), 1); ok(f.state !== 'ct'); ok(f.events.length === 0 || true); });
  t('block enters and leaves with the button', () => { const f = makeFighter(); const o = makeFighter('megumi', 1); f.setState('idle', {}); run(f, o, frame({ block: true }), 2); eq(f.state, 'block'); run(f, o, frame(), 2); eq(f.state, 'idle'); });
  t('jump leaves the ground and lands', () => { const f = makeFighter(); const o = makeFighter('megumi', 1); f.setState('idle', {}); run(f, o, frame({ jump: true }), 1); eq(f.state, 'jump'); ok(!f.grounded); run(f, o, frame(), 200); ok(['land', 'idle'].includes(f.state)); ok(f.grounded); });
  t('a deliberate dash bursts; a lazy one does not', () => { const f = makeFighter(); const o = makeFighter('megumi', 1); f.setState('idle', {}); run(f, o, frame({ move: { x: 0, z: -1 }, dash: true }), 1); eq(f.state, 'dash'); ok(f.dashBurstT > 0, 'burst armed'); const g = makeFighter(); g.setState('idle', {}); run(g, o, frame({ move: { x: 0, z: -1 } }), 30); run(g, o, frame({ move: { x: 0, z: -1 }, dash: true }), 1); eq(g.state, 'dash'); eq(g.dashBurstT, 0, 'no burst from a held stick'); });
  t('a light hit puts the victim in hitstun for the move\'s frames, then idle', () => { const f = makeFighter(); const o = makeFighter('megumi', 1); f.setState('idle', {}); const r = f.applyHit({ dmg: 4, kb: 2, kbY: 0, hitstun: 14, type: 'normal', attacker: o, basic: true }, {}); eq(r, 'hit'); eq(f.state, 'hitLight'); run(f, o, frame(), 15); eq(f.state, 'idle'); });
  t('a launcher then a knockdown: launched -> falls -> knockdown -> getup -> idle', () => { const f = makeFighter(); const o = makeFighter('megumi', 1); f.setState('idle', {}); f.applyHit({ dmg: 8, kb: 3, kbY: 7.8, hitstun: 26, type: 'launcher', attacker: o, basic: true }, {}); eq(f.state, 'launched'); ok(!f.grounded); until(f, o, 'knockdown'); until(f, o, 'getup'); until(f, o, 'idle'); });
  t('tech: jump on touchdown rises early', () => { const f = makeFighter(); const o = makeFighter('megumi', 1); f.setState('idle', {}); f.applyHit({ dmg: 8, kb: 3, kbY: 0, hitstun: 26, type: 'knockdown', attacker: o, basic: true }, {}); eq(f.state, 'knockdown'); run(f, o, frame({ jump: true }), 1); eq(f.state, 'techRise'); ok(f.iFrames >= 26); });
  t('a mistimed tech locks the attempt', () => { const f = makeFighter(); const o = makeFighter('megumi', 1); f.setState('idle', {}); f.applyHit({ dmg: 8, kb: 3, kbY: 0, hitstun: 26, type: 'knockdown', attacker: o, basic: true }, {}); run(f, o, frame(), 20); run(f, o, frame({ jump: true }), 1); eq(f.state, 'knockdown'); ok(f.techLock); });
  t('MAX_CE grows on landed punches and refills CURRENT; backlash halves it', () => { const f = makeFighter(); const before = f.res.maxCE; f.gainMaxCE(6); eq(f.res.maxCE, before + 6); eq(f.res.curCE, f.res.maxCE); f.backlash = 5; f.gainMaxCE(6); eq(f.res.maxCE, before + 9); f.res.maxCE = 100; f.res.curCE = 100; ok(f.charged); ok(f.ultReady); f.consumeFullBar(); eq(f.res.maxCE, f.cfg.stats.startMaxCE); eq(f.res.curCE, 0); });
  t('damage multiplier composes buffs, void debuff and chains', () => { const f = makeFighter(); const base = f.dmgMult; f.addBuff('x', 5, { dmg: 1.3 }); near(f.dmgMult, base * 1.3); f.buffs.voidDebuff = 3; near(f.dmgMult, base * 1.3 * 0.85); });
  t('Toji has no cursed energy: techniques are free, no ult gate', () => { const f = makeFighter('toji'); ok(f.noCE); ok(f.spendCE(999)); ok(!f.charged); });
}
