// NOBARA — Straw Doll Technique. The setup zoner. Her damage does not come
// from where she is standing; it comes from what she has already done to you.
// Fragile and average in a straight fight, terrifying if she has been allowed
// to land hits.
//
// ---------------------------------------------------------------------------
// THE SECOND RESOURCE: ESSENCE 依代
// ---------------------------------------------------------------------------
// Gathered FROM the opponent, not generated by her. Every clean hit she lands
// takes a little of them; detonating a nail stuck in their body takes more;
// a Black Flash takes a lot. It accumulates on a dedicated HUD meter that both
// players can read, because the opponent has to know how much of themselves
// she is holding.
//
// It is spent on RESONANCE, which deals damage regardless of distance, line of
// sight or defence. It persists for the whole round and is lost ONLY when
// spent — so running away does not reset the threat, it only delays it.
//
// Canon-correct: NO DOMAIN EXPANSION. D-pad Right is a burst ultimate with the
// faster startup and lower commitment every non-domain ultimate here gets.
import { withDefaults } from './schema.js';

export const NOBARA = withDefaults({
  id: 'nobara', name: 'NOBARA', title: 'FIRST YEAR — STRAW DOLL',
  stats: {
    // The most fragile human in the roster. Average legs, average stamina,
    // below-average health and the shortest normals on anyone with two arms.
    hp: 92, walkSpeed: 2.7, runSpeed: 5.2, dashSpeed: 8.6, jumpVel: 8.8,
    startMaxCE: 40, ceRegen: 2.2, ceGainPerPunch: 6, damageScale: 0.96,
    stamina: 100, staminaRegen: 23, dashDrain: 26
  },

  // ---- ESSENCE -------------------------------------------------------------
  // Taken at the single choke point every clean hit already passes through
  // (Fighter.applyHit), so there is no damage route that can gather it twice
  // and none that can miss it. Blocked hits, armoured hits and chip take
  // NOTHING: she has to actually connect.
  essence: {
    max: 100, start: 0,
    perLight: 2.4,        // a jab in the string
    perHeavy: 3.4,        // the launcher, and any 'heavy' technique connect
    perKnockdown: 5.0,    // her hammer ender and the heavy
    perCT: 3.0,           // a technique connect
    // 5.0 rather than the 6.5 this started at: four in-body detonations paid
    // 38 Essence in one press, which is most of a Resonance handed over for
    // free on top of the blast damage. See the note on ct1.blastDmg.
    perNail: 5.0,         // detonating a nail embedded in their BODY
    perBlackFlash: 22,    // the payoff for the read
    lowWarn: 8
  },

  // 3-hit hammer string. SHORT reach — 1.25 to 1.35 against a roster norm of
  // 1.35 to 1.55 — average damage, and fast recovery so the string is safe to
  // throw and safe to leave. Every hit gathers Essence. The third knocks down.
  punches: [
    { dmg: 4, startup: 5, active: 3, recovery: 10, reach: 1.25, kb: 1.5, kbY: 0, hitstun: 13, type: 'light', step: 1.7 },
    { dmg: 5, startup: 6, active: 3, recovery: 11, reach: 1.28, kb: 2.0, kbY: 0, hitstun: 15, type: 'light', step: 1.7 },
    { dmg: 8, startup: 9, active: 4, recovery: 18, reach: 1.35, kb: 4.2, kbY: 0, hitstun: 28, type: 'knockdown', step: 1.9 }
  ],
  // HEAVY — THE FULL SWING: everything she has behind one hammer blow. It is
  // the hardest thing she can do with her hands and it is still less than most
  // of the roster's, which is the point.
  heavy: {
    name: 'Full Swing', dmg: 14, startup: 18, active: 5, recovery: 30,
    reach: 1.75, kb: 5.4, hitstun: 30, step: 2.3, staminaCost: 20, armorFrames: 0
  },

  ct1: {
    // HAIRPIN 簪 — nails bound with cursed energy, thrown. They EMBED: in the
    // opponent, or in the floor where they miss, and a nail in the floor is a
    // trap for the rest of its fuse. They detonate on the fuse, or early on a
    // follow-up input once the cap is reached (RB stops throwing and becomes
    // the detonator — see Fighter.startCT).
    //
    // A nail detonating in a BODY gathers extra Essence; one detonating in the
    // floor does not. That is the whole reason to aim.
    name: 'Hairpin', cost: 9,
    startup: 12, active: 3, recovery: 16,
    effect: 'nobara_hairpin',
    dmg: 5,                // the nail itself, on the way in
    // MEASURED AND TUNED DOWN. At blastDmg 10 a full cap of four nails all
    // landing in the BODY and detonated together took 57.6 off a stationary
    // Yuji for 36 cursed energy — and paid her 38 Essence on top, which is
    // another ~17 of Resonance. Roughly three quarters of a health bar out of
    // one resource cycle. Against a moving opponent most nails go into the
    // floor instead and it is nowhere near that, but the best case has to be
    // survivable too. 8 puts the all-in-body case at ~50.
    blastDmg: 8,           // the detonation
    radius: 2.0,           // detonation radius, so a floor nail is a real trap
    speed: 24, range: 15,
    fuse: 2.6,             // seconds before it goes off on its own
    maxNails: 4,           // hard cap; the 5th press detonates instead
    kb: 1.2, kbY: 0, hitstun: 12,
    blastKb: 3.2, blastKbY: 1.2, blastHitstun: 22,
    clip: 'ct1', detonateClip: 'detonate'
  },

  ct2: {
    // ---------------------------------------------------------------------
    // RESONANCE 共鳴 — THE PAYOFF, AND THE MOST DANGEROUS MOVE IN THE ROSTER
    // ---------------------------------------------------------------------
    // It consumes Essence and deals damage to the opponent at ANY range,
    // through ANY defence. It cannot be blocked, cannot be dodged, ignores
    // walls and distance entirely, and it reaches through domain barriers. It
    // is routed through the SAME sure-hit bypass the domains already use
    // (`sureHit: true, unblockable: true`), so it is not a second
    // implementation of "ignores defences" — it is the existing one.
    //
    // IT SPENDS EVERYTHING. There is no partial spend and no charge input: RT
    // takes the whole meter and the damage scales with what was in it. That is
    // what makes "dump it all for one enormous hit" and "tap it repeatedly for
    // chip" the SAME button — the choice is when you press it, which is a real
    // decision made under pressure rather than a menu.
    //
    // THE COUNTERPLAY IS THE CHANNEL. The doll and the nail come up in her
    // hands, there is a distinct sound cue, and she stands there unable to act
    // for `channelBase + essence * channelPerEssence` frames. At 8 Essence
    // that is 26 frames; at a full 100 it is 46 — nearly eight tenths of a
    // second of a stationary, silent, completely open Nobara. Killing her
    // during it is the answer, and the bigger the Resonance the bigger the
    // window she gives you.
    //
    // The Essence is committed on the ACTIVATION frame, not on the press, so
    // an interrupted channel costs her the cursed energy and the frames but
    // NOT the round's savings. Same ruling Sukuna's finger already gets.
    name: 'Resonance', cost: 14,
    startup: 26, active: 1, recovery: 26,   // startup is recomputed per cast
    effect: 'nobara_resonance',
    minEssence: 8,
    base: 2, perEssence: 0.40,
    channelBase: 24, channelPerEssence: 0.22,
    clip: 'ct2'
  },

  // ---- BLACK FLASH ---------------------------------------------------------
  // The SAME system Yuji uses — the same `openBlackFlash` helper, the same
  // `bfT` window, the same `effects.blackFlash()` payload. Nothing about his
  // version is touched.
  //
  // What differs is where the window comes from and which button confirms it.
  // Yuji's Flash IS his special: any of his techniques opens a window and
  // B cashes it. Nobara's SPECIAL is a dedicated committed strike
  // that opens the window, and PUNCH cashes it — `confirm: 'punch'` is the one
  // field that says so, and Yuji's config does not have it, so his path is
  // bit-identical to what it was.
  blackFlash: {
    delay: 6, window: 6, dmgMult: 2.5, chainDmg: 0.06,
    ceRefund: 18, maxSpike: 6, reach: 2.2,
    confirm: 'punch',
    // Hers pays in ESSENCE and a damage window rather than in a big cursed
    // energy refund. Yuji has no `bonus`, so his refund path is unchanged.
    bonus: { essence: 22, dmgMult: 1.22, duration: 8 }
  },
  special: {
    key: 'nobara_blackflash', name: 'BLACK FLASH',
    cost: 10, cooldown: 7,
    startup: 14, active: 4, recovery: 26,
    effect: 'nobara_bf_strike',
    dmg: 11, reach: 1.90, arc: 1.5, kb: 2.4, kbY: 0, hitstun: 20,
    clip: 'bfStrike'
  },

  ultimate: {
    // RESONANCE: FULL RELEASE. Non-domain, standard gate, full bar, standard
    // backlash — and it consumes ALL stored Essence at nearly double the
    // per-point rate of a normal Resonance.
    //
    // This is deliberately a bill, not a button. With little Essence stored it
    // is a wasted ultimate and it should feel like one; with a round's worth
    // banked it is the biggest single hit in the game (100 Essence = 80,
    // against Hollow Purple's 45 and the Jackpot Blast's 30).
    kind: 'burst', name: 'RESONANCE: FULL RELEASE', jpName: '共鳴・全解放',
    startup: 34, active: 1, recovery: 34,
    effect: 'nobara_full_release', clip: 'ult',
    base: 8, perEssence: 0.72,
    kb: 7, kbY: 3, hitstun: 44
    // No `backlash` block — see the note on Choso's SUPERNOVA. A burst
    // ultimate's cost in this project is `consumeFullBar()` and nothing else,
    // which is what every other non-domain ultimate on the roster pays. Hers
    // costs a second thing on top that none of theirs do: the entire Essence
    // meter, which is a round's worth of landed hits.
  },

  domain: null,            // canon-correct: Nobara has no Domain Expansion
  simpleDomainDrain: 19,
  barrierBreak: { ceDrain: 32, chip: 22 },
  // Yuta stores the technique that IS one. Resonance is not portable: it is
  // powered by a piece of the opponent that Nobara took and Yuta did not, and
  // a Copy slot that reached through every defence in the game for free would
  // be the single worst thing in this roster. He gets the nail.
  copyEffect: { effect: 'nobara_hairpin', dmg: 6, name: 'Copied: Hairpin' }
});
