// ============================================================================
// THE JACKPOT THEME — an ORIGINAL composition, synthesised at runtime.
// ----------------------------------------------------------------------------
// No copyrighted music is used, embedded, sampled or referenced anywhere in
// this file. Every note below is written here, and every sound is generated by
// the same Web Audio primitives the rest of audio/sfx.js uses — there is no
// audio asset behind it.
//
// THE PIECE
//   Title (ours):  "HOUSE ALWAYS WINS"
//   Key:           B-flat major
//   Tempo:         168 BPM, 4/4
//   Form:          one 8-bar loop, 11.43 s, looping seamlessly for the whole
//                  99-second Jackpot window
//   Progression:   | Bb | F | Cm | F | Bb | Eb | F | Bb |
//   Character:     a brass-band march — oom-pah bass on the eighths, stabbed
//                  triads on the backbeat, a bright staccato lead over the
//                  top, glockenspiel doubling the long notes an octave up, and
//                  a coin-drop chime on the last sixteenth of every half bar.
//                  Relentlessly, tastelessly happy, and completely indifferent
//                  to what is happening on screen. That gap is the joke.
//
// It ducks under impacts (Sfx routes its loudest cues through duck()) and it
// STOPS DEAD when Jackpot ends — no fade. The silence afterwards is scored.
// ============================================================================

const BPM = 168;
const STEP = 60 / BPM / 4;        // one sixteenth, ~0.0893 s
const STEPS = 128;                // 8 bars
const LOOKAHEAD = 0.35;           // seconds of events scheduled in advance

const mtof = m => 440 * Math.pow(2, (m - 69) / 12);

// ---- the score -------------------------------------------------------------
// [startStep, midi, lengthInSteps]. Bb4 = 70.
const LEAD = [
  // bar 1 — the hook: two pickup Bb, then the arpeggio up to F
  [0, 70, 2], [2, 70, 2], [4, 74, 4], [8, 77, 4], [12, 74, 4],
  // bar 2 — leans on F, falls away
  [16, 77, 6], [22, 75, 2], [24, 74, 4], [28, 72, 4],
  // bar 3 — the minor bar, lifted rather than darkened
  [32, 72, 2], [34, 72, 2], [36, 75, 4], [40, 79, 4], [44, 75, 4],
  // bar 4 — one long F and a bar of air
  [48, 77, 8],
  // bar 5 — the answer, an octave up
  [64, 82, 4], [68, 81, 2], [70, 79, 2], [72, 77, 4], [76, 74, 4],
  // bar 6 — the climb
  [80, 75, 4], [84, 77, 4], [88, 79, 8],
  // bar 7 — run to the top
  [96, 77, 2], [98, 79, 2], [100, 81, 4], [104, 82, 4], [108, 77, 4],
  // bar 8 — land on the tonic and hand back to bar 1
  [112, 82, 8]
];

// one chord per bar: [rootMidi, minor?]
const CHORDS = [
  [46, 0], [41, 0], [48, 1], [41, 0], [46, 0], [51, 0], [41, 0], [46, 0]
];

export class JackpotTheme {
  constructor(sfx) {
    this.sfx = sfx;
    this.playing = false;
    this.bus = null;
    this.step = 0;
    this.nextTime = 0;
    this.level = 0.30;      // master level for the whole piece
    this.duckT = 0;
    this.duckLevel = 1;
    this._gain = -1;
  }

  get ctx() { return this.sfx.ctx; }

  start() {
    this.sfx.ensure();
    if (!this.ctx || this.playing) return;
    this.stop();
    this.bus = this.ctx.createGain();
    this.bus.gain.value = this.level;
    this._gain = this.level;
    // a gentle high shelf keeps the square-wave stack from getting shrill
    const tone = this.ctx.createBiquadFilter();
    tone.type = 'lowpass';
    tone.frequency.value = 5200;
    tone.Q.value = 0.4;
    this.bus.connect(tone);
    tone.connect(this.sfx.master);
    this.tone = tone;
    this.step = 0;
    this.nextTime = this.ctx.currentTime + 0.06;
    this.playing = true;
    this.sfx.theme = this;   // Sfx.hit()/crit()/slam() duck through this handle
  }

  // Hard stop. Cancels the envelope and mutes the bus on the spot: the cut is
  // part of the design, so there is deliberately no release here.
  stop() {
    this.playing = false;
    if (this.sfx.theme === this) this.sfx.theme = null;
    if (!this.bus) return;
    const t = this.ctx?.currentTime ?? 0;
    try {
      this.bus.gain.cancelScheduledValues(t);
      this.bus.gain.setValueAtTime(0, t);
    } catch (e) { /* ignore */ }
    const bus = this.bus, tone = this.tone;
    setTimeout(() => { try { bus.disconnect(); tone?.disconnect(); } catch (e) { } }, 400);
    this.bus = null;
    this.tone = null;
    this.duckT = 0;
    this.duckLevel = 1;
  }

  // pull the music down under an impact, then let it back up
  duck(level = 0.55, seconds = 0.16) {
    if (!this.playing) return;
    this.duckLevel = Math.min(this.duckLevel, level);
    this.duckT = Math.max(this.duckT, seconds);
  }

  update(dt) {
    if (!this.playing || !this.ctx || !this.bus) return;
    if (this.duckT > 0) {
      this.duckT -= dt;
      if (this.duckT <= 0) this.duckLevel = 1;
    }
    const want = this.level * this.duckLevel;
    if (Math.abs(want - this._gain) > 0.004) {
      this._gain = want;
      this.bus.gain.setTargetAtTime(want, this.ctx.currentTime, 0.045);
    }
    // fixed-grid lookahead scheduler: everything for the next LOOKAHEAD
    // seconds is queued on the audio clock, so frame hitches never swing it
    const horizon = this.ctx.currentTime + LOOKAHEAD;
    let guard = 0;
    while (this.nextTime < horizon && guard++ < 64) {
      this._emitStep(this.step, this.nextTime);
      this.step = (this.step + 1) % STEPS;
      this.nextTime += STEP;
    }
  }

  // ---- one sixteenth -------------------------------------------------------
  _emitStep(s, at) {
    const bar = (s / 16) | 0;
    const inBar = s % 16;
    const [root, minor] = CHORDS[bar];

    // BASS — oom-pah on the eighths: root on the beat, fifth off it
    if (inBar % 4 === 0) this._bass(mtof(root), at, STEP * 1.7);
    else if (inBar % 4 === 2) this._bass(mtof(root + 7), at, STEP * 1.5);

    // BRASS STABS — the backbeat block chord
    if (inBar === 4 || inBar === 12 || (bar === 7 && inBar === 14)) {
      const third = root + 12 + (minor ? 3 : 4);
      for (const m of [root + 12, third, root + 19]) this._brass(mtof(m), at, STEP * 1.6, 0.055);
    }

    // DRUMS
    if (inBar % 8 === 0) this._kick(at);
    if (inBar % 8 === 4) this._snare(at);
    if (inBar % 2 === 0) this._hat(at, inBar % 4 === 0 ? 0.028 : 0.045);
    // a fill into the top of the loop
    if (bar === 7 && inBar >= 12) this._snare(at, 0.16 + (inBar - 12) * 0.05);

    // LEAD + GLOCKENSPIEL DOUBLE
    for (const [st, midi, len] of LEAD) {
      if (st !== s) continue;
      const dur = len * STEP * 0.92;
      this._brass(mtof(midi), at, dur, 0.10);
      this._brass(mtof(midi) * 1.005, at, dur, 0.07);   // detuned second horn
      if (len >= 4) this._bell(mtof(midi + 12), at, Math.min(0.5, dur));
    }

    // COIN CHIME — the parlor sparkle, last sixteenth of each half bar
    if (inBar === 7 || inBar === 15) {
      this._bell(mtof(root + 24 + (inBar === 15 ? 7 : 4)), at, 0.22, 0.05);
    }
  }

  // ---- voices --------------------------------------------------------------
  _env(at, dur, peak, attack = 0.006) {
    const g = this.ctx.createGain();
    g.gain.setValueAtTime(0.0001, at);
    g.gain.linearRampToValueAtTime(peak, at + attack);
    g.gain.exponentialRampToValueAtTime(0.0008, at + dur);
    g.connect(this.bus);
    return g;
  }

  _bass(f, at, dur) {
    const g = this._env(at, dur, 0.20, 0.004);
    const o = this.ctx.createOscillator();
    o.type = 'square';
    o.frequency.setValueAtTime(f, at);
    const sub = this.ctx.createOscillator();
    sub.type = 'sine';
    sub.frequency.setValueAtTime(f / 2, at);
    const sg = this.ctx.createGain();
    sg.gain.value = 0.7;
    o.connect(g);
    sub.connect(sg); sg.connect(g);
    o.start(at); o.stop(at + dur + 0.03);
    sub.start(at); sub.stop(at + dur + 0.03);
  }

  _brass(f, at, dur, peak) {
    const g = this._env(at, dur, peak, 0.010);
    const filt = this.ctx.createBiquadFilter();
    filt.type = 'lowpass';
    filt.frequency.setValueAtTime(f * 6.5, at);
    filt.frequency.exponentialRampToValueAtTime(Math.max(300, f * 2.6), at + dur);
    filt.Q.value = 0.8;
    const o = this.ctx.createOscillator();
    o.type = 'sawtooth';
    // the tiniest pitch scoop into the note — brass does not start in tune
    o.frequency.setValueAtTime(f * 0.986, at);
    o.frequency.linearRampToValueAtTime(f, at + 0.022);
    o.connect(filt); filt.connect(g);
    o.start(at); o.stop(at + dur + 0.03);
  }

  _bell(f, at, dur, peak = 0.07) {
    const g = this._env(at, dur, peak, 0.002);
    const o = this.ctx.createOscillator();
    o.type = 'triangle';
    o.frequency.setValueAtTime(f, at);
    const h = this.ctx.createOscillator();
    h.type = 'sine';
    h.frequency.setValueAtTime(f * 2.76, at);   // inharmonic partial = metal
    const hg = this.ctx.createGain();
    hg.gain.value = 0.28;
    o.connect(g);
    h.connect(hg); hg.connect(g);
    o.start(at); o.stop(at + dur + 0.03);
    h.start(at); h.stop(at + dur + 0.03);
  }

  _kick(at) {
    const g = this._env(at, 0.20, 0.34, 0.002);
    const o = this.ctx.createOscillator();
    o.type = 'sine';
    o.frequency.setValueAtTime(128, at);
    o.frequency.exponentialRampToValueAtTime(44, at + 0.11);
    o.connect(g);
    o.start(at); o.stop(at + 0.24);
  }

  _snare(at, peak = 0.16) {
    const src = this.ctx.createBufferSource();
    src.buffer = this.sfx.noiseBuf;
    const f = this.ctx.createBiquadFilter();
    f.type = 'bandpass';
    f.frequency.value = 1900;
    f.Q.value = 0.7;
    const g = this._env(at, 0.13, peak, 0.001);
    src.connect(f); f.connect(g);
    src.start(at, Math.random() * 0.4); src.stop(at + 0.17);
  }

  _hat(at, peak) {
    const src = this.ctx.createBufferSource();
    src.buffer = this.sfx.noiseBuf;
    const f = this.ctx.createBiquadFilter();
    f.type = 'highpass';
    f.frequency.value = 7200;
    const g = this._env(at, 0.05, peak, 0.001);
    src.connect(f); f.connect(g);
    src.start(at, Math.random() * 0.4); src.stop(at + 0.08);
  }
}
